[package]
name = "ton-vanity-search"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
ed25519-dalek = "2.0"
sha2 = "0.10"
base64 = "0.21"
crc32fast = "1.3"
rayon = "1.7"
hex = "0.4"
